name: Sync Monorepo Subfolders

on:
  push:
    branches:
      - main

jobs:
  sync-ahrefs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo-a
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Split ahrefs subtree
        run: |
          git subtree split --prefix=ahrefs -b split-ahrefs

      - name: Check secret exists and length
        env:
          MY_SECRET: ${{ secrets.SYNC_REPO_TOKEN }}
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "MY_SECRET is empty or not set"
          else
            echo "MY_SECRET is set"
            echo "MY_SECRET length: ${#MY_SECRET}"

      - name: Push ahrefs to RepoSEO
        run: |
          echo "${{ secrets.SYNC_REPO_TOKEN }}"
          git push https://x-access-token:${{ secrets.SYNC_REPO_TOKEN }}@github.com/TestMainRepo/RepoSEO.git split-ahrefs:main --force
