name: Sync Monorepo Subfolders

on:
  push:
    branches:
      - main

jobs:
  sync-ahrefs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo-a
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Split ahrefs subtree
        run: |
          git subtree split --prefix=ahrefs -b split-ahrefs

      - name: Push ahrefs to RepoSEO
        env:
          TOKEN: ${{ secrets.SYNC_REPO_TOKEN }}
        run: |
          echo "TOKEN LEN: ${#TOKEN}"
          
          git remote add ahrefs https://github.com/TestMainRepo/RepoSEO.git
          git remote set-url ahrefs https://x-access-token:$TOKEN@github.com/TestMainRepo/RepoSEO.git
      
          git push ahrefs split-ahrefs:main --force
